# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='vb.Team'),
        ),
    ]
