# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0002_bet_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_number',
            field=models.IntegerField(default=1),
        ),
    ]
