# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0003_fixture_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
