# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0004_auto_20160430_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vb.BettingUser'),
        ),
    ]
