# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0006_auto_20160430_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettinguser',
            name='bet_admin',
            field=models.BooleanField(default=False),
        ),
    ]
