# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0007_bettinguser_bet_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('match',)]),
        ),
    ]
