# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0008_auto_20160430_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinMultiplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb.Fixture')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vb.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='winmultiplier',
            unique_together=set([('match', 'team')]),
        ),
    ]
