# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0009_auto_20160501_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_transfer', models.BooleanField(default=True)),
            ],
        ),
    ]
