# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0010_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='freeze_bet_before',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
