# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0012_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vb.Themes'),
        ),
    ]
