# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0013_configuration_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
