# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vb', '0014_auto_20160502_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='max_receiver_amount',
            field=models.PositiveIntegerField(default=2000000),
        ),
        migrations.AddField(
            model_name='configuration',
            name='max_transfer_amount',
            field=models.PositiveIntegerField(default=200000),
        ),
    ]
